language : php

env:
  global:
    - 'FTP_USER=septianwebprog'
    - 'FTP_PASS=septian123'

script:

  - "curl -u $FTP_USER:$FTP_PASS ftp://files.000webhost.com -Q 'mkd public_html'"
  - "curl -u $FTP_USER:$FTP_PASS ftp://files.000webhost.com -Q 'mkd public_html/assets'"
  - "curl -u $FTP_USER:$FTP_PASS ftp://files.000webhost.com -Q 'mkd public_html/template'"

  - "curl -T form-edit.php -u $FTP_USER:$FTP_PASS ftp://files.000webhost.com/public_html/"
  - "curl -T hapus.php -u $FTP_USER:$FTP_PASS ftp://files.000webhost.com/public_html/"
  - "curl -T input.php -u $FTP_USER:$FTP_PASS ftp://files.000webhost.com/public_html/"
  - "curl -T koneksi.php -u $FTP_USER:$FTP_PASS ftp://files.000webhost.com/public_html/"
  - "curl -T index.php -u $FTP_USER:$FTP_PASS ftp://files.000webhost.com/public_html/"
  - "curl -T update.php -u $FTP_USER:$FTP_PASS ftp://files.000webhost.com/public_html/"
  - "curl -T simpan.php -u $FTP_USER:$FTP_PASS ftp://files.000webhost.com/public_html/"
  - "curl -T /assets/ -u $FTP_USER:$FTP_PASS ftp://files.000webhost.com/public_html/"
  - "curl -T /template/ -u $FTP_USER:$FTP_PASS ftp://files.000webhost.com/public_html/"
  - "curl -T simpan.php -u $FTP_USER:$FTP_PASS ftp://files.000webhost.com/public_html/"
